
package br.com.lheme.estoque.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.3.7
 * 2020-09-22T22:10:41.286-03:00
 * Generated source version: 3.3.7
 */

@WebFault(name = "AutorizacaoFault", targetNamespace = "http://ws.estoque.lheme.com.br/")
public class AutorizacaoException extends Exception {

    private br.com.lheme.estoque.ws.InfoFault autorizacaoFault;

    public AutorizacaoException() {
        super();
    }

    public AutorizacaoException(String message) {
        super(message);
    }

    public AutorizacaoException(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public AutorizacaoException(String message, br.com.lheme.estoque.ws.InfoFault autorizacaoFault) {
        super(message);
        this.autorizacaoFault = autorizacaoFault;
    }

    public AutorizacaoException(String message, br.com.lheme.estoque.ws.InfoFault autorizacaoFault, java.lang.Throwable cause) {
        super(message, cause);
        this.autorizacaoFault = autorizacaoFault;
    }

    public br.com.lheme.estoque.ws.InfoFault getFaultInfo() {
        return this.autorizacaoFault;
    }
}
