package br.com.lheme.estoque.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.7
 * 2020-09-22T22:10:41.336-03:00
 * Generated source version: 3.3.7
 *
 */
@WebService(targetNamespace = "http://ws.estoque.lheme.com.br/", name = "EstoqueWS")
@XmlSeeAlso({ObjectFactory.class})
public interface EstoqueWS {

    @WebMethod
    @Action(input = "http://ws.estoque.lheme.com.br/EstoqueWS/todosOsItensRequest", output = "http://ws.estoque.lheme.com.br/EstoqueWS/todosOsItensResponse")
    @RequestWrapper(localName = "todosOsItens", targetNamespace = "http://ws.estoque.lheme.com.br/", className = "br.com.lheme.estoque.ws.TodosOsItens")
    @ResponseWrapper(localName = "todosOsItensResponse", targetNamespace = "http://ws.estoque.lheme.com.br/", className = "br.com.lheme.estoque.ws.TodosOsItensResponse")
    @WebResult(name = "itens", targetNamespace = "")
    public br.com.lheme.estoque.ws.ListaItens todosOsItens(

        @WebParam(name = "filtros", targetNamespace = "")
        br.com.lheme.estoque.ws.Filtros filtros
    );

    @WebMethod
    @Action(input = "http://ws.estoque.lheme.com.br/EstoqueWS/cadastrarItemRequest", output = "http://ws.estoque.lheme.com.br/EstoqueWS/cadastrarItemResponse", fault = {@FaultAction(className = AutorizacaoException.class, value = "http://ws.estoque.lheme.com.br/EstoqueWS/cadastrarItem/Fault/AutorizacaoException")})
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "cadastrarItemResponse", targetNamespace = "http://ws.estoque.lheme.com.br/", partName = "result")
    public CadastrarItemResponse cadastrarItem(

        @WebParam(partName = "parameters", name = "cadastrarItem", targetNamespace = "http://ws.estoque.lheme.com.br/")
        CadastrarItem parameters,
        @WebParam(partName = "tokenUsuario", name = "tokenUsuario", targetNamespace = "http://ws.estoque.lheme.com.br/", header = true)
        TokenUsuario tokenUsuario
    ) throws AutorizacaoException;
}
